/**
 * WebiGeeks — Question Seeder
 * Run: node src/scripts/seedQuestions.js
 *
 * Upserts all questions from the frontend question bank into MongoDB.
 * Safe to re-run — uses questionId as the unique key (no duplicates).
 */

import mongoose from 'mongoose';
import { MONGO_URI } from '../config.js';
import { Question } from '../models/Question.js';

// ── Raw question data (copied from frontend question files) ─────────────────
// Each entry: { id, topicId?, experienceLevel, type, question, answer, code?, explanation?, output?, choices? }
// topicId and trackId are added by the TOPIC_MAP below.

const TOPIC_MAP = {
  // MERN Stack
  'html':                    'mern-stack',
  'css':                     'mern-stack',
  'flexbox':                 'mern-stack',
  'javascript':              'mern-stack',
  'react':                   'mern-stack',
  'node-js':                 'mern-stack',
  'express-js':              'mern-stack',
  'mongodb':                 'mern-stack',
  'mongoose':                'mern-stack',
  'authentication':          'mern-stack',
  'bcrypt':                  'mern-stack',
  'jwt':                     'mern-stack',
  'passport-local':          'mern-stack',
  'passport-google-oauth20': 'mern-stack',
  // Data Analytics
  'excel':       'data-analytics',
  'sql':         'data-analytics',
  'python':      'data-analytics',
  'pandas':      'data-analytics',
  'numpy':       'data-analytics',
  'matplotlib':  'data-analytics',
  'tableau':     'data-analytics',
  'power-bi':    'data-analytics',
};

// Derive topic from the question's id prefix (e.g. "html-f1" → "html")
function deriveTopicId(questionId) {
  // id format: <topic>-<level><number>  e.g. html-f1, node-j2, power-bi-m1
  // We match against known topic keys (longest match wins)
  const sorted = Object.keys(TOPIC_MAP).sort((a, b) => b.length - a.length);
  for (const topic of sorted) {
    const safe = topic.replace(/-/g, '-'); // same
    if (questionId.startsWith(safe + '-')) return topic;
  }
  // Fallback: take everything before the last -<level><digit>
  return questionId.replace(/-[fmj]\d+$/, '');
}

// ── Inline question bank ─────────────────────────────────────────────────────
// This mirrors the frontend files exactly so the DB stays in sync.
// When you add questions to the frontend files, add them here too (or run a
// shared importer script from a shared JSON — that's the next evolution).

const RAW_QUESTIONS = [
  // ─── HTML ───────────────────────────────────────────────────────────────
  { id:'html-f1', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between HTML elements and HTML tags?', answer:'A tag is the markup syntax written in angle brackets (e.g., <p>, </p>). An element is the complete structure — the opening tag, the content inside, and the closing tag together. Self-closing tags like <img> and <br> form a complete element by themselves.' },
  { id:'html-f2', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between HTML and HTML5?', answer:'HTML5 is the latest version (2014) and added semantic elements (<header>, <footer>, <article>, <nav>, <section>), native audio/video support (<audio>, <video>), the <canvas> element for 2D drawing, local storage, new input types (email, date, range), and the Geolocation API. HTML5 also deprecated presentational tags like <font> and <center>.' },
  { id:'html-f3', experienceLevel:'fresher', type:'conceptual', question:'What is the purpose of the DOCTYPE declaration?', answer:'<!DOCTYPE html> tells the browser which version of HTML is being used so it renders the page in standards mode. Without it, browsers fall into "quirks mode" and may render layout differently.' , code:'<!DOCTYPE html>\n<html lang="en">\n  <head><title>My Page</title></head>\n  <body><h1>Hello</h1></body>\n</html>' },
  { id:'html-f4', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between block-level and inline elements? Give examples.', answer:'Block-level elements start on a new line and take up the full width of their parent (<div>, <p>, <h1>–<h6>, <ul>, <table>, <section>). Inline elements only take up as much width as their content and flow within text (<span>, <a>, <img>, <strong>, <em>, <input>).' },
  { id:'html-f5', experienceLevel:'fresher', type:'conceptual', question:'What are semantic HTML elements and why do they matter?', answer:'Semantic elements like <header>, <nav>, <main>, <article>, <section>, <aside>, and <footer> clearly describe their purpose. They help: screen readers navigate content for accessibility, search engines understand page structure for SEO, and developers read the code.' },
  { id:'html-f6', experienceLevel:'fresher', type:'practical', question:'How do you create an accessible form with email, password, and a submit button?', answer:'Use <label> with matching for/id attributes, appropriate input types, and required attribute for validation.', code:'<form action="/login" method="POST">\n  <label for="email">Email</label>\n  <input type="email" id="email" name="email" required />\n  <label for="password">Password</label>\n  <input type="password" id="password" name="password" required minlength="8" />\n  <button type="submit">Sign In</button>\n</form>' },
  { id:'html-f7', experienceLevel:'fresher', type:'conceptual', question:'What is the alt attribute on <img> and why is it important?', answer:'The alt attribute provides text that describes the image. It matters for accessibility (screen readers), SEO (search engines index alt text), and as a fallback when the image fails to load.' },
  { id:'html-f8', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between the GET and POST methods in an HTML form?', answer:'GET appends form data to the URL as query strings — visible, bookmarkable, but insecure for sensitive data. POST sends data in the request body — not visible in the URL, required for passwords and file uploads.' },
  { id:'html-f9', experienceLevel:'fresher', type:'output', question:'Guess the rendered result', code:'<p>I <strong>love</strong> <em>coding</em></p>', output:'"love" in bold, "coding" in italics, all on one line inside a paragraph', explanation:'<strong> renders bold with semantic importance; <em> renders italic with semantic emphasis.', choices:[{label:'"love" bold, "coding" italic',correct:true},{label:'All text bold',correct:false},{label:'Three separate paragraphs',correct:false},{label:'Error — cannot nest inline tags',correct:false}] },
  { id:'html-f10', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between <section>, <article>, and <div>?', answer:'<div> is a generic non-semantic container for layout. <section> groups thematically related content that belongs to a larger whole. <article> represents self-contained, independently distributable content like a blog post or news article.' },
  { id:'html-f11', experienceLevel:'fresher', type:'conceptual', question:'How do you open a link in a new tab securely?', answer:'Use target="_blank" and always add rel="noopener noreferrer" — without it, the new page gains access to window.opener which can be exploited for phishing (tabnapping).', code:'<a href="https://example.com" target="_blank" rel="noopener noreferrer">Visit</a>' },
  { id:'html-f13', experienceLevel:'fresher', type:'output', question:'What does this meta tag do?', code:'<meta name="viewport" content="width=device-width, initial-scale=1.0">', output:'Makes the page responsive — sets the viewport width equal to the device screen width', explanation:'Without this tag, mobile browsers render the page at desktop width and then scale it down.', choices:[{label:'Makes the page mobile-responsive',correct:true},{label:'Sets the page background color',correct:false},{label:'Adds a page icon',correct:false},{label:'Enables dark mode',correct:false}] },
  { id:'html-j1', experienceLevel:'junior', type:'conceptual', question:'What are ARIA roles and when should you use them?', answer:'ARIA roles, states, and properties add accessibility semantics to elements that are not natively accessible. Use ARIA only when HTML semantics are insufficient — e.g., role="dialog" on a custom modal, aria-label on an icon-only button. The first rule of ARIA: use native HTML elements before adding ARIA attributes.' },
  { id:'html-j2', experienceLevel:'junior', type:'conceptual', question:'What is the difference between async and defer on a <script> tag?', answer:'Both download the script in parallel with HTML parsing. async executes immediately when downloaded (good for independent third-party scripts). defer executes only after HTML parsing is complete maintaining script order (good for DOM-manipulating scripts).' },
  { id:'html-j4', experienceLevel:'junior', type:'conceptual', question:'What is the data-* attribute and how is it accessed in JavaScript?', answer:'Custom data-* attributes store extra data on HTML elements without non-standard attributes. They are accessible via el.dataset.camelCaseName in JS.', code:'<button data-product-id="42" data-action="add-to-cart">Add</button>\n\nconst btn = document.querySelector("button");\nconsole.log(btn.dataset.productId);  // "42"' },
  { id:'html-j5', experienceLevel:'junior', type:'conceptual', question:'What is the difference between localStorage, sessionStorage, and cookies?', answer:'localStorage persists until cleared, ~5MB. sessionStorage persists only until the tab closes and is isolated to that tab. Cookies are sent with every HTTP request and can be httpOnly/Secure/SameSite for security.' },
  { id:'html-j7', experienceLevel:'junior', type:'output', question:'What is the difference in behaviour between these two inputs?', code:'<input type="text" />\n<input type="search" />', output:'type="search" adds a clear (×) button in most browsers, triggers the search event on Enter, and carries different semantics for accessibility.', explanation:'Semantic input types improve UX with browser-native features.', choices:[{label:'search shows a clear button and triggers search events',correct:true},{label:'They are identical',correct:false},{label:'search disables auto-complete',correct:false},{label:'text validates email format',correct:false}] },
  { id:'html-m1', experienceLevel:'mid', type:'conceptual', question:'What is the Critical Rendering Path and how does HTML structure affect it?', answer:'The CRP is: Parse HTML → Build DOM → Parse CSS → Build CSSOM → Render Tree → Layout → Paint. Optimisations: inline critical CSS, use defer/async on scripts, preload important resources with <link rel="preload">, lazy-load below-the-fold content.' },
  { id:'html-m2', experienceLevel:'mid', type:'conceptual', question:'How does the browser parse HTML when it encounters a <script> tag without defer/async?', answer:'The HTML parser STOPS and waits for the script to download, parse, and execute before continuing. This is why scripts at the bottom of <body> improve performance. defer and async solve this by parallelising download.' },
  { id:'html-m4', experienceLevel:'mid', type:'conceptual', question:'What are Web Components and their three main standards?', answer:'(1) Custom Elements — define new HTML tag names. (2) Shadow DOM — encapsulate markup and styles. (3) HTML Templates — <template> and <slot> for reusable markup.' },
  { id:'html-m7', experienceLevel:'mid', type:'conceptual', question:'What are resource hints (preload, prefetch, preconnect, dns-prefetch)?', answer:'preload: Download immediately, high priority (critical current-page resources). prefetch: Download at low priority for next navigation. preconnect: Pre-establish DNS + TCP + TLS. dns-prefetch: Pre-resolve DNS only — lighter than preconnect.' },

  // ─── CSS ────────────────────────────────────────────────────────────────
  { id:'css-f1', experienceLevel:'fresher', type:'conceptual', question:'What is CSS specificity and how is it calculated?', answer:'Specificity determines which CSS rule wins when multiple rules target the same element. Score: Inline=1000, ID=100, Class=10, Element=1. Higher total wins. !important overrides all specificity.' },
  { id:'css-f2', experienceLevel:'fresher', type:'conceptual', question:'Explain the CSS Box Model. What is the difference between content-box and border-box?', answer:'Every element is content + padding + border + margin. content-box (default): width applies to content only — total rendered width = width + padding + border. border-box: width includes padding and border.' },
  { id:'css-f3', experienceLevel:'fresher', type:'output', question:'Guess the total rendered width', code:'.box {\n  width: 200px;\n  padding: 20px;\n  border: 5px solid;\n  box-sizing: content-box;\n}', output:'250px — content(200) + left padding(20) + right padding(20) + left border(5) + right border(5)', explanation:'content-box adds padding and border outside the declared width.', choices:[{label:'250px',correct:true},{label:'200px',correct:false},{label:'220px',correct:false},{label:'245px',correct:false}] },
  { id:'css-f5', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between display:none, visibility:hidden, and opacity:0?', answer:'display:none removes element from layout — takes no space, inaccessible. visibility:hidden hides but preserves space. opacity:0 invisible but still takes space AND responds to pointer events.' },
  { id:'css-f6', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between static, relative, absolute, fixed, sticky positioning?', answer:'static: default, no offset. relative: offset from own position, stays in flow. absolute: removed from flow, positioned relative to nearest positioned ancestor. fixed: relative to viewport. sticky: in flow until scroll threshold, then fixed within scroll container.' },
  { id:'css-f7', experienceLevel:'fresher', type:'practical', question:'How do you centre a div both horizontally and vertically?', answer:'Three modern methods:', code:'/* Flexbox */\n.parent { display: flex; justify-content: center; align-items: center; }\n/* Grid */\n.parent { display: grid; place-items: center; }\n/* Absolute + transform */\n.child { position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); }' },
  { id:'css-f9', experienceLevel:'fresher', type:'output', question:'Guess the font size of the paragraph', code:'html { font-size: 16px; }\n.parent { font-size: 1.5em; }\n.child { font-size: 1.5em; }', output:'36px — root 16px × 1.5 = 24px (parent), then 24px × 1.5 = 36px (child)', explanation:'em compounds — each nested em multiplies against its parent computed font-size.', choices:[{label:'36px (em compounds)',correct:true},{label:'24px',correct:false},{label:'16px',correct:false},{label:'1.5px',correct:false}] },
  { id:'css-f11', experienceLevel:'fresher', type:'practical', question:'How do you create a CSS custom property (variable) and use it?', answer:'Declare with -- prefix on :root (global) or any element (scoped). Access with var().', code:':root {\n  --primary-color: #4f46e5;\n  --border-radius: 8px;\n}\n.button {\n  background: var(--primary-color);\n  border-radius: var(--border-radius);\n}' },
  { id:'css-j1', experienceLevel:'junior', type:'conceptual', question:'What is CSS Grid and how does it differ from Flexbox?', answer:'Flexbox is one-dimensional (row OR column). CSS Grid is two-dimensional (rows AND columns simultaneously). Use Flexbox for component-level layout; Grid for page-level layout. They complement each other.' },
  { id:'css-j4', experienceLevel:'junior', type:'practical', question:'How do you implement a dark mode using CSS custom properties?', answer:'Define light/dark colour palettes and override with prefers-color-scheme.', code:':root { --bg: #ffffff; --text: #1e293b; }\n@media (prefers-color-scheme: dark) {\n  :root { --bg: #0f172a; --text: #f1f5f9; }\n}\nbody { background: var(--bg); color: var(--text); }' },
  { id:'css-j7', experienceLevel:'junior', type:'output', question:'Guess the visual result of this CSS', code:'.container {\n  display: grid;\n  grid-template-columns: 1fr 2fr 1fr;\n  width: 400px;\n}', output:'Three columns: left 100px, centre 200px, right 100px', explanation:'1+2+1=4 parts; each unit = 400/4 = 100px.', choices:[{label:'100px | 200px | 100px',correct:true},{label:'133px each',correct:false},{label:'50px | 300px | 50px',correct:false},{label:'Error',correct:false}] },
  { id:'css-m1', experienceLevel:'mid', type:'conceptual', question:'What are CSS Cascade Layers (@layer)?', answer:'@layer creates named CSS layers with explicit specificity order. Lower layers lose to higher regardless of selector specificity — eliminates !important battles.', code:'@layer reset, base, components, utilities;\n@layer reset { * { margin: 0; } }' },
  { id:'css-m5', experienceLevel:'mid', type:'output', question:'Is this animation GPU-accelerated?', code:'.slide {\n  animation: move 1s ease;\n}\n@keyframes move {\n  from { left: 0; }\n  to { left: 200px; }\n}', output:'NOT GPU-accelerated — left causes layout reflow. Use transform: translateX(200px) instead.', explanation:'Only transform and opacity are GPU-composited by default.', choices:[{label:'Not GPU-accelerated — left causes layout reflow',correct:true},{label:'GPU-accelerated because animation is used',correct:false},{label:'GPU-accelerated in Chrome only',correct:false},{label:'Depends on browser',correct:false}] },

  // ─── JavaScript ───────────────────────────────────────────────────────────
  { id:'js-f1', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between var, let, and const?', answer:'var: function-scoped, hoisted and initialized to undefined, can be re-declared. let: block-scoped, hoisted but in Temporal Dead Zone, can be reassigned. const: block-scoped, must be initialized at declaration, cannot be reassigned.' },
  { id:'js-f2', experienceLevel:'fresher', type:'conceptual', question:'What is hoisting in JavaScript?', answer:'Hoisting moves declarations to the top of their scope. var declarations are hoisted and set to undefined. function declarations are fully hoisted. let/const are hoisted but remain in the Temporal Dead Zone — accessing them before declaration throws ReferenceError.' },
  { id:'js-f3', experienceLevel:'fresher', type:'output', question:'Guess the output', code:'console.log(x);\nconsole.log(y);\nvar x = 5;\nlet y = 10;', output:'undefined (var hoisted)\nReferenceError for y (let is in Temporal Dead Zone)', explanation:'var is hoisted and initialized to undefined. let is hoisted but cannot be accessed before its declaration.', choices:[{label:'undefined, then ReferenceError',correct:true},{label:'5, 10',correct:false},{label:'undefined, undefined',correct:false},{label:'ReferenceError for both',correct:false}] },
  { id:'js-f4', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between == and ===?', answer:'== (loose equality) performs type coercion before comparing. "5" == 5 is true. === (strict equality) compares value AND type. "5" === 5 is false. Always prefer === in production code.' },
  { id:'js-f5', experienceLevel:'fresher', type:'output', question:'Guess the output', code:'console.log(null == undefined);\nconsole.log(null === undefined);\nconsole.log(0 == false);\nconsole.log(0 === false);', output:'true, false, true, false', explanation:'null==undefined is a special coercion case. 0 and false coerce via ==. === requires same type.', choices:[{label:'true, false, true, false',correct:true},{label:'false, false, false, false',correct:false},{label:'true, true, true, true',correct:false},{label:'true, false, false, false',correct:false}] },
  { id:'js-f7', experienceLevel:'fresher', type:'practical', question:'How do you remove duplicates from an array?', answer:'Use Set which only stores unique values.', code:'const arr = [1, 2, 2, 3, 3, 4];\nconst unique = [...new Set(arr)]; // [1, 2, 3, 4]' },
  { id:'js-f10', experienceLevel:'fresher', type:'output', question:'Guess the output', code:'const arr = [1, 2, 3];\narr.push(4);\nconst arr2 = arr;\narr2.push(5);\nconsole.log(arr.length);', output:'5', explanation:'Arrays are reference types. arr2 = arr copies the reference. Both variables point to the same array.', choices:[{label:'5',correct:true},{label:'4',correct:false},{label:'3',correct:false},{label:'Error — cannot reassign const',correct:false}] },
  { id:'js-j1', experienceLevel:'junior', type:'conceptual', question:'What is a closure in JavaScript?', answer:'A closure is a function that retains access to its outer scope\'s variables even after the outer function has returned. Uses: data privacy, function factories, memoization, event handlers with configuration.', code:'function makeCounter(start = 0) {\n  let count = start;\n  return {\n    increment: () => ++count,\n    value: () => count,\n  };\n}\nconst counter = makeCounter(10);\ncounter.increment(); // 11' },
  { id:'js-j3', experienceLevel:'junior', type:'output', question:'Guess the console output order', code:"setTimeout(() => console.log('A'), 0);\nPromise.resolve().then(() => console.log('B'));\nconsole.log('C');\nqueueMicrotask(() => console.log('D'));", output:'C, B, D, A', explanation:'Sync runs first (C). Microtasks (Promise → B, queueMicrotask → D). Then macrotask (setTimeout → A).', choices:[{label:'C, B, D, A',correct:true},{label:'C, A, B, D',correct:false},{label:'A, B, C, D',correct:false},{label:'C, D, B, A',correct:false}] },
  { id:'js-j4', experienceLevel:'junior', type:'conceptual', question:'What are call(), apply(), and bind()?', answer:'All three set the this context. call(thisArg, arg1, arg2) invokes immediately with args listed. apply(thisArg, [argsArray]) invokes immediately with args as array. bind(thisArg) returns a new function with this permanently bound.' },
  { id:'js-j5', experienceLevel:'junior', type:'practical', question:'Implement a debounce function.', answer:'Debounce delays execution until a pause in events.', code:'function debounce(fn, wait) {\n  let timerId;\n  return function (...args) {\n    clearTimeout(timerId);\n    timerId = setTimeout(() => fn.apply(this, args), wait);\n  };\n}' },
  { id:'js-m1', experienceLevel:'mid', type:'conceptual', question:'Explain CommonJS vs ES Modules in Node.js.', answer:'CommonJS (require/module.exports): synchronous, runtime evaluation, can conditionally require. ES Modules (import/export): static analysis (enables tree-shaking), async, live bindings. Use ESM for new projects.' },
  { id:'js-m3', experienceLevel:'mid', type:'conceptual', question:'What are WeakMap and WeakSet?', answer:'WeakMap allows object keys to be garbage-collected when no other references exist — unlike Map which prevents GC. WeakSet holds objects weakly. Use cases: private metadata on DOM elements, avoiding memory leaks. Neither is iterable.' },

  // ─── React ───────────────────────────────────────────────────────────────
  { id:'react-f1', experienceLevel:'fresher', type:'conceptual', question:'What is the Virtual DOM and how does React use it?', answer:'The Virtual DOM is a lightweight in-memory representation of the real DOM. When state changes, React re-renders the virtual DOM, diffs it against the previous tree (reconciliation), and applies only the minimum real DOM mutations. This is faster than re-rendering the entire DOM.' },
  { id:'react-f3', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between props and state?', answer:'Props are read-only data passed FROM parent TO child — the child cannot modify them. State is mutable data OWNED by the component — when it changes via useState setter, the component re-renders.' },
  { id:'react-f4', experienceLevel:'fresher', type:'output', question:'Guess when this useEffect fires', code:'useEffect(() => {\n  console.log("effect ran");\n}, [count]);', output:'On initial mount AND every time the count variable changes', explanation:'Dependency array with values = run on mount + when those values change.', choices:[{label:'On mount and when count changes',correct:true},{label:'Only when count changes (not on mount)',correct:false},{label:'Only once on mount',correct:false},{label:'After every render',correct:false}] },
  { id:'react-f5', experienceLevel:'fresher', type:'practical', question:'How do you correctly update state that depends on the previous value?', answer:'Use the updater form of setState to avoid stale closure bugs.', code:'const [count, setCount] = useState(0);\n// ✅ CORRECT — functional update:\nsetCount((prev) => prev + 1);\n// ❌ RISKY — stale count in async context:\nsetCount(count + 1);' },
  { id:'react-f7', experienceLevel:'fresher', type:'output', question:'How many times does this re-render when the button is clicked once?', code:'function Counter() {\n  const [count, setCount] = useState(0);\n  console.log("render");\n  return <button onClick={() => {\n    setCount(c => c + 1);\n    setCount(c => c + 1);\n  }}>Click</button>;\n}', output:'Once — React 18 batches all setState calls in an event handler into a single re-render', explanation:'React 18 introduced automatic batching for all updates in event handlers.', choices:[{label:'Once (React batches both setStates)',correct:true},{label:'Twice — one per setState',correct:false},{label:'Zero — nothing changed visually',correct:false},{label:'Three',correct:false}] },
  { id:'react-j1', experienceLevel:'junior', type:'conceptual', question:'What is prop drilling and how does Context API solve it?', answer:'Prop drilling is passing data through multiple intermediate components that don\'t use it. Context API creates a provider at a high level and any descendant can consume it with useContext() — skipping intermediates.' },
  { id:'react-j3', experienceLevel:'junior', type:'conceptual', question:'When should you use useCallback and useMemo?', answer:'useMemo memoizes a computed VALUE. useCallback memoizes a FUNCTION reference. Use them to prevent children wrapped in React.memo from re-rendering due to new references. Only use when profiling shows a real issue — both add overhead.' },
  { id:'react-j4', experienceLevel:'junior', type:'output', question:'Guess the value of count after all setStates run', code:'const [count, setCount] = useState(0);\n\nfunction handleClick() {\n  setCount(count + 1);\n  setCount(count + 1);\n  setCount(count + 1);\n}', output:'1 — all three calls use the same stale count (0), each sets it to 1', explanation:'Without the functional updater form, all setState calls in one render capture the same count=0.', choices:[{label:'1 (all use stale count=0)',correct:true},{label:'3 (each increments)',correct:false},{label:'0',correct:false},{label:'2',correct:false}] },
  { id:'react-m1', experienceLevel:'mid', type:'conceptual', question:'What is concurrent rendering in React 18?', answer:'Concurrent rendering lets React pause, interrupt, and resume rendering. Features: automatic batching, Transitions (useTransition marks non-urgent updates), Suspense improvements, useDeferredValue, createRoot API.' },
  { id:'react-m3', experienceLevel:'mid', type:'conceptual', question:'What are React Server Components?', answer:'Server Components run only on the server — access databases directly, never ship JS to client. Client Components (use client) run on both server and client — have interactivity, state, effects. RSCs pass data to client components as props. Foundation of Next.js App Router.' },

  // ─── Node.js ─────────────────────────────────────────────────────────────
  { id:'node-f1', experienceLevel:'fresher', type:'conceptual', question:'What is Node.js and why is it popular for backend development?', answer:'Node.js is a runtime that executes JavaScript outside the browser, built on V8. It uses an event-driven, non-blocking I/O model — one thread handles many concurrent connections by delegating I/O to the OS. Popular for API servers, real-time apps, and developer tooling.' },
  { id:'node-f2', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between synchronous and asynchronous code in Node.js?', answer:'Synchronous code blocks the event loop — no other code runs until it finishes. Asynchronous code delegates work and registers a callback — the event loop remains free. Blocking the event loop with CPU-heavy sync code is a critical performance mistake in Node.js.' },
  { id:'node-f5', experienceLevel:'fresher', type:'output', question:'Guess the console output order', code:"console.log('1');\nsetTimeout(() => console.log('2'), 0);\nPromise.resolve().then(() => console.log('3'));\nconsole.log('4');", output:'1, 4, 3, 2', explanation:'Sync runs first (1, 4). Microtask (Promise → 3) before macrotask (setTimeout → 2).', choices:[{label:'1, 4, 3, 2',correct:true},{label:'1, 2, 3, 4',correct:false},{label:'1, 4, 2, 3',correct:false},{label:'1, 3, 4, 2',correct:false}] },
  { id:'node-f7', experienceLevel:'fresher', type:'practical', question:'How do you use environment variables in Node.js?', answer:'Store sensitive config in a .env file and load with dotenv.', code:"import 'dotenv/config';\nconst port = process.env.PORT ?? 3000;\nconst secret = process.env.JWT_SECRET;\nif (!secret) throw new Error('JWT_SECRET is required');" },
  { id:'node-j1', experienceLevel:'junior', type:'conceptual', question:'Explain the Node.js event loop phases in order.', answer:'(1) timers — expired setTimeout/setInterval. (2) pending callbacks — I/O errors. (3) idle/prepare — internal. (4) poll — retrieves new I/O, blocks if empty. (5) check — setImmediate(). (6) close callbacks. Between each phase, microtask queue (Promises, process.nextTick) drains completely.' },
  { id:'node-j3', experienceLevel:'junior', type:'conceptual', question:'What are Node.js streams and what are the four types?', answer:'Streams process data in chunks without loading everything into memory. Types: (1) Readable (data source), (2) Writable (data destination), (3) Duplex (both), (4) Transform (duplex that transforms data). Use .pipeline() for safe stream composition.' },
  { id:'node-m1', experienceLevel:'mid', type:'conceptual', question:'How does Node.js clustering work?', answer:'Node.js is single-threaded — uses one CPU core. The cluster module forks multiple worker processes (one per CPU core) that share the same port. Use PM2 in cluster mode for production. Workers should use Redis for shared state.' },
  { id:'node-m5', experienceLevel:'mid', type:'output', question:'What happens when this runs in high-traffic Node.js code?', code:'// Inside a request handler:\nconst data = require("fs").readFileSync("./config.json", "utf8");', output:'Blocks the entire event loop on every request — all other requests freeze.', explanation:'readFileSync in a request handler is one of the most common Node.js performance mistakes.', choices:[{label:'Blocks event loop — all requests freeze',correct:true},{label:'Fine — OS caches the file',correct:false},{label:'Node.js makes sync ops async automatically',correct:false},{label:'Only blocks if file > 1MB',correct:false}] },

  // ─── Express.js ──────────────────────────────────────────────────────────
  { id:'exp-f1', experienceLevel:'fresher', type:'conceptual', question:'What is Express.js and what does it add over Node\'s built-in http module?', answer:'Express adds: (1) Routing with route parameters and HTTP method handlers, (2) Middleware pipeline, (3) Request/response helpers (res.json(), req.params, req.query, req.body), (4) Error handling, (5) Static file serving.' },
  { id:'exp-f2', experienceLevel:'fresher', type:'conceptual', question:'What is middleware in Express?', answer:'Middleware are functions in the request-response pipeline receiving req, res, and next. Calling next() passes control to the next middleware. Error-handling middleware has 4 parameters: (err, req, res, next).' },
  { id:'exp-f4', experienceLevel:'fresher', type:'output', question:'What happens when a request hits this middleware and no route matches?', code:"app.use((req, res, next) => {\n  console.log(req.method, req.url);\n  next();\n});\n// No matching routes defined", output:'Middleware logs the request; Express\'s default 404 "Cannot GET /path" is sent', explanation:'next() passes to the next handler. If nothing handles it, Express sends a built-in 404.', choices:[{label:'Logs the request; Express default 404 sends',correct:true},{label:'Hangs — no response sent',correct:false},{label:'Error thrown',correct:false},{label:'next() re-runs the first middleware',correct:false}] },
  { id:'exp-j1', experienceLevel:'junior', type:'conceptual', question:'How do you implement global error handling in Express?', answer:'Define an error-handling middleware with FOUR parameters (err, req, res, next). Place it AFTER all routes. Pass errors with next(err).', code:'app.use((err, req, res, next) => {\n  const status = err.status ?? 500;\n  res.status(status).json({ message: err.message });\n});' },
  { id:'exp-j3', experienceLevel:'junior', type:'conceptual', question:'What is Express Router and why use it?', answer:'express.Router() creates a mini Express app — its own middleware and routes — mounted at a path. Use it to: break routes into logical modules, apply middleware to a group of routes, version APIs (/api/v1, /api/v2).' },
  { id:'exp-m1', experienceLevel:'mid', type:'conceptual', question:'What security headers should every production Express API have?', answer:'Use helmet middleware: Content-Security-Policy, X-Frame-Options, X-Content-Type-Options, Strict-Transport-Security. Additionally: rate limiting (express-rate-limit), input sanitisation (mongo-sanitize for NoSQL injection), CORS configuration.' },

  // ─── MongoDB ─────────────────────────────────────────────────────────────
  { id:'mdb-f1', experienceLevel:'fresher', type:'conceptual', question:'What is MongoDB and how does it differ from SQL databases?', answer:'MongoDB is a NoSQL document database storing BSON documents in collections. No fixed schema, no JOINs (use $lookup), horizontal scaling built-in. SQL excels for relational data; MongoDB for flexible, hierarchical, or high-volume data.' },
  { id:'mdb-f4', experienceLevel:'fresher', type:'output', question:'What does the _id field contain in a newly inserted document?', code:"db.users.insertOne({ name: 'Arjun' });", output:'{ _id: ObjectId("507f1f77bcf86cd799439011"), name: "Arjun" } — auto-generated 12-byte ObjectId', explanation:'MongoDB auto-generates an ObjectId encoding timestamp, random bytes, and counter.', choices:[{label:'An ObjectId (12-byte BSON type)',correct:true},{label:'An auto-incrementing integer',correct:false},{label:'A UUID v4 string',correct:false},{label:'Operation fails — _id is required',correct:false}] },
  { id:'mdb-f9', experienceLevel:'fresher', type:'output', question:'What happens to this update without an operator?', code:"db.users.updateOne({ name: 'Ali' }, { age: 30 });", output:'Document becomes { _id: ObjectId(...), age: 30 } — the name field is DELETED', explanation:'Without $set, updateOne replaces the entire document. Always use $set: { age: 30 }.', choices:[{label:'Document becomes { _id, age:30 } — name deleted',correct:true},{label:'Only age updated, name preserved',correct:false},{label:'Error — update requires an operator',correct:false},{label:'No change',correct:false}] },
  { id:'mdb-j1', experienceLevel:'junior', type:'conceptual', question:'What is the MongoDB aggregation pipeline?', answer:'The aggregation pipeline processes documents through sequential stages. Common stages: $match (filter early), $group (aggregate), $project (reshape), $sort, $limit, $lookup (left outer join), $unwind (deconstruct array).' },
  { id:'mdb-j5', experienceLevel:'junior', type:'conceptual', question:'What are MongoDB indexes and how do you decide which fields to index?', answer:'Indexes enable fast query lookups without full collection scans. Index fields appearing in: WHERE conditions, sort clauses, JOIN foreign keys. ESR Rule for compound indexes: Equality → Sort → Range. Over-indexing hurts write performance.' },
  { id:'mdb-m1', experienceLevel:'mid', type:'conceptual', question:'What are MongoDB transactions and when do you need them?', answer:'Multi-document transactions provide ACID properties across multiple collections. Needed when multiple writes must all succeed or all fail together. Transactions are slower than single-document operations — design schema to minimise their need.' },

  // ─── Mongoose ────────────────────────────────────────────────────────────
  { id:'mong-f1', experienceLevel:'fresher', type:'conceptual', question:'What is Mongoose and what problem does it solve?', answer:'Mongoose is an ODM for MongoDB in Node.js. It adds: schema definition with type validation, model layer with CRUD methods, middleware hooks (pre-save, post-save), query helpers, virtuals (computed fields), and population (reference resolution).' },
  { id:'mong-f3', experienceLevel:'fresher', type:'output', question:'What happens when you create a user without the required email?', code:"await User.create({ name: 'Rahul', password: 'abc12345' });", output:'Throws ValidationError: Path `email` is required.', explanation:'Mongoose validates before sending to MongoDB. create() never reaches the database.', choices:[{label:'Throws ValidationError: email is required',correct:true},{label:'Document saves with null email',correct:false},{label:'MongoDB rejects it',correct:false},{label:'No error',correct:false}] },
  { id:'mong-j1', experienceLevel:'junior', type:'practical', question:'How do you implement a pre-save hook to hash a password?', answer:'Check isModified() to avoid re-hashing on unrelated updates.', code:"userSchema.pre('save', async function (next) {\n  if (!this.isModified('password')) return next();\n  const salt = await bcrypt.genSalt(10);\n  this.password = await bcrypt.hash(this.password, salt);\n  next();\n});" },
  { id:'mong-j4', experienceLevel:'junior', type:'output', question:'What does findByIdAndUpdate return by default?', code:"const user = await User.findByIdAndUpdate(id, { $set: { name: 'New Name' } });", output:'The OLD document (before update)', explanation:'Add { new: true } option to get the updated document.', choices:[{label:'The old document (before update)',correct:true},{label:'The new updated document',correct:false},{label:'null',correct:false},{label:'The update result object',correct:false}] },
  { id:'mong-m1', experienceLevel:'mid', type:'conceptual', question:'What are Mongoose plugins?', answer:'Plugins are reusable schema extensions added to multiple schemas without repeating code. Common uses: soft-delete (add deletedAt field), audit trail, paginate (add static paginate() method), toJSON transformations.' },

  // ─── Authentication ──────────────────────────────────────────────────────
  { id:'auth-f1', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between authentication and authorisation?', answer:'Authentication: "Who are you?" — verifying identity. Authorisation: "What can you do?" — determining permissions after identity is confirmed. Both are separate concerns and handled in separate middleware layers.' },
  { id:'auth-f2', experienceLevel:'fresher', type:'conceptual', question:'Why should passwords never be stored in plain text?', answer:'If the database is breached, all passwords are exposed. Hashing is one-way. Salting prevents rainbow table attacks. bcrypt at cost=10 takes ~100ms — computationally infeasible to brute-force at scale.' },
  { id:'auth-f4', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between session-based and token-based authentication?', answer:'Session-based: server stores session data; client gets a session ID cookie; every request requires a DB lookup. Stateful. Token-based (JWT): all user data is in a signed token; server only verifies the signature. Stateless. JWT scales horizontally; sessions are easier to invalidate.' },
  { id:'auth-j1', experienceLevel:'junior', type:'conceptual', question:'What are the three parts of a JWT?', answer:'Header (base64url): algorithm and type "JWT". Payload (base64url): claims (sub, iat, exp, role). Signature: HMAC of header+payload using the secret key. The payload is ENCODED, not encrypted — anyone can decode it. Only the signature proves it was not tampered with.' },
  { id:'auth-j3', experienceLevel:'junior', type:'conceptual', question:'What is CSRF and how do you protect a REST API?', answer:'CSRF tricks authenticated users into making requests via malicious pages. For REST APIs using JWT Bearer tokens: CSRF is largely mitigated as browsers don\'t auto-send custom headers cross-origin. If using cookies: add SameSite=Strict or SameSite=Lax.' },
  { id:'auth-m1', experienceLevel:'mid', type:'conceptual', question:'How do you implement refresh token rotation securely?', answer:'Issue new access AND refresh tokens on every /auth/refresh call. Invalidate old refresh token immediately. If an already-used refresh token is presented (token reuse detection), invalidate the entire token family — sign of token theft. Store refresh token HASH in DB.' },

  // ─── JWT ─────────────────────────────────────────────────────────────────
  { id:'jwt-f1', experienceLevel:'fresher', type:'conceptual', question:'What is a JWT and what is it used for?', answer:'JWT is a compact, URL-safe token format encoding claims as a JSON object signed with HMAC or RSA. Used for API authentication and information exchange between services. JWTs are stateless — no session storage needed.' },
  { id:'jwt-f2', experienceLevel:'fresher', type:'practical', question:'How do you sign and verify a JWT in Node.js?', answer:'Always specify algorithms and issuer in verify() to prevent algorithm confusion attacks.', code:"const token = jwt.sign({ sub: user._id, role: user.role }, process.env.JWT_SECRET, { expiresIn: '15m' });\n\nconst decoded = jwt.verify(token, process.env.JWT_SECRET, { algorithms: ['HS256'] });" },
  { id:'jwt-f4', experienceLevel:'fresher', type:'output', question:'What does the decoded payload contain?', code:"const token = jwt.sign({ sub: '507f...', role: 'admin' }, secret, { expiresIn: '1h' });\nconst decoded = jwt.decode(token);\nconsole.log(decoded);", output:'{ sub: "507f...", role: "admin", iat: <timestamp>, exp: <timestamp+3600> }', explanation:'jwt.decode() decodes without signature verification. In production always use jwt.verify().', choices:[{label:'{ sub, role, iat, exp } — all claims visible',correct:true},{label:'Returns null',correct:false},{label:'Encrypted blob',correct:false},{label:'Throws error — secret required',correct:false}] },
  { id:'jwt-j2', experienceLevel:'junior', type:'conceptual', question:'How would you implement JWT logout?', answer:'JWTs cannot be "deleted". Strategies: (1) Short TTL — accept tokens valid until expiry. (2) Token blocklist — store invalidated JTI in Redis with TTL. (3) Refresh token invalidation — invalidate refresh token; access token expires shortly.' },
  { id:'jwt-m1', experienceLevel:'mid', type:'conceptual', question:'What is the difference between HS256 and RS256?', answer:'HS256 (HMAC): single shared secret — same key signs and verifies. Good for single services. RS256 (RSA): asymmetric — private key signs, public key verifies. Any service can verify knowing only the public key. Essential for microservices.' },

  // ─── bcrypt ──────────────────────────────────────────────────────────────
  { id:'bcr-f1', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between hashing and encryption?', answer:'Hashing is ONE-WAY — cannot be reversed. The same input always produces the same hash. Encryption is TWO-WAY — data can be decrypted given the key. For passwords: hash (bcrypt). For sensitive data to be retrieved: encrypt (AES-256).' },
  { id:'bcr-f4', experienceLevel:'fresher', type:'output', question:'Are these two bcrypt hashes of the same password identical?', code:"const h1 = await bcrypt.hash('myPassword', 10);\nconst h2 = await bcrypt.hash('myPassword', 10);\nconsole.log(h1 === h2);", output:'false — bcrypt generates a new random salt for each call, producing a different hash every time', explanation:'Different salts prevent rainbow tables. bcrypt.compare() extracts the salt from the stored hash to verify.', choices:[{label:'false — random salt makes each hash unique',correct:true},{label:'true — same password same hash',correct:false},{label:'Error',correct:false},{label:'undefined',correct:false}] },
  { id:'bcr-j1', experienceLevel:'junior', type:'conceptual', question:'How does bcrypt.compare() work internally?', answer:'The stored hash contains the version identifier, cost factor, and the 22-character salt + hash. bcrypt.compare() extracts the salt, hashes the plain password with that same salt, and compares. You never need to store the salt separately.' },

  // ─── SQL ─────────────────────────────────────────────────────────────────
  { id:'sql-f1', experienceLevel:'fresher', type:'conceptual', question:'What are the five categories of SQL commands?', answer:'DDL (CREATE, ALTER, DROP, TRUNCATE), DML (INSERT, UPDATE, DELETE), DQL (SELECT), DCL (GRANT, REVOKE), TCL (COMMIT, ROLLBACK, SAVEPOINT).' },
  { id:'sql-f2', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between WHERE and HAVING?', answer:'WHERE filters rows BEFORE grouping — cannot use aggregate functions. HAVING filters AFTER GROUP BY — can use aggregate functions. WHERE is for rows; HAVING is for groups.' },
  { id:'sql-f3', experienceLevel:'fresher', type:'conceptual', question:'What are the different types of JOINs in SQL?', answer:'INNER JOIN: only matching rows. LEFT JOIN: all left + matching right (NULL if no match). RIGHT JOIN: all right + matching left. FULL OUTER JOIN: all rows from both. CROSS JOIN: cartesian product. SELF JOIN: table joined to itself.' },
  { id:'sql-f6', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between DELETE, TRUNCATE, and DROP?', answer:'DELETE: removes specific rows with optional WHERE, transaction-logged, can rollback. TRUNCATE: removes ALL rows instantly, minimally logged, much faster, cannot use WHERE. DROP: removes entire table including structure — irreversible.' },
  { id:'sql-j1', experienceLevel:'junior', type:'conceptual', question:'What is a subquery and the difference between correlated vs non-correlated?', answer:'Non-correlated subquery: runs once independently. Correlated subquery: references outer query columns — runs once per outer row (can be slow). Prefer JOINs or CTEs over correlated subqueries for performance.' },
  { id:'sql-j2', experienceLevel:'junior', type:'conceptual', question:'What are window functions? Difference between ROW_NUMBER, RANK, DENSE_RANK?', answer:'Window functions compute across related rows without collapsing groups. ROW_NUMBER(): unique sequential. RANK(): same rank for ties, skips numbers (1,1,3). DENSE_RANK(): same rank for ties, no skipping (1,1,2). Use DENSE_RANK for Nth ranking.' },
  { id:'sql-m1', experienceLevel:'mid', type:'conceptual', question:'What are ACID properties?', answer:'Atomicity: all operations succeed or all are rolled back. Consistency: DB remains valid before and after. Isolation: concurrent transactions do not interfere. Durability: committed data survives crashes.' },
  { id:'sql-m4', experienceLevel:'mid', type:'conceptual', question:'How do you optimise a slow SQL query?', answer:'(1) EXPLAIN/EXPLAIN ANALYZE — identify COLLSCAN. (2) Add indexes on WHERE, JOIN, ORDER BY columns. (3) Rewrite correlated subqueries as JOINs. (4) Avoid SELECT *. (5) Push filters early. (6) Consider partitioning. (7) Materialise expensive CTEs.' },

  // ─── Python ──────────────────────────────────────────────────────────────
  { id:'py2-f2', experienceLevel:'fresher', type:'output', question:'Guess the output', code:'x = [1, 2, 3]\ny = x\ny.append(4)\nprint(x)', output:'[1, 2, 3, 4]', explanation:'y = x copies the reference. Both point to the same list object.', choices:[{label:'[1, 2, 3, 4]',correct:true},{label:'[1, 2, 3]',correct:false},{label:'Error',correct:false},{label:'[4]',correct:false}] },
  { id:'py2-j3', experienceLevel:'junior', type:'output', question:'Guess the output — mutable default argument', code:'def add_item(item, lst=[]):\n    lst.append(item)\n    return lst\n\nprint(add_item("a"))\nprint(add_item("b"))', output:'["a"]\n["a", "b"]', explanation:'Python mutable defaults are evaluated once and shared across calls — a classic Python gotcha.', choices:[{label:'["a"] then ["a","b"] (shared list)',correct:true},{label:'["a"] then ["b"] (new list each call)',correct:false},{label:'Error',correct:false},{label:'["a","b"] both times',correct:false}] },
  { id:'py2-m1', experienceLevel:'mid', type:'conceptual', question:'What is the Python GIL?', answer:'The GIL (Global Interpreter Lock) allows only ONE thread to execute Python bytecode at a time. For CPU-bound tasks: use multiprocessing or ProcessPoolExecutor. For I/O-bound tasks: GIL is released during I/O waits — threads work. asyncio is better for I/O with thousands of concurrent operations.' },

  // ─── Pandas ──────────────────────────────────────────────────────────────
  { id:'pd2-f1', experienceLevel:'fresher', type:'conceptual', question:'What is a Pandas DataFrame vs a Series?', answer:'A Series is a one-dimensional labeled array (like one column with an index). A DataFrame is a two-dimensional table — a dictionary where each key is a column name and each value is a Series.' },
  { id:'pd2-f3', experienceLevel:'fresher', type:'output', question:'What does .isnull().sum() return?', code:'df.isnull().sum()', output:'A Series indexed by column names with the count of missing (NaN) values in each column', explanation:'.isnull() creates a boolean DataFrame (True=NaN). .sum() adds True=1 per column.', choices:[{label:'Count of NaN values per column',correct:true},{label:'Total null count (one number)',correct:false},{label:'Boolean DataFrame same shape as df',correct:false},{label:'Rows with any null',correct:false}] },
  { id:'pd2-f4', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between .loc[] and .iloc[]?', answer:'.loc[] is LABEL-based — use actual index labels and column names. .iloc[] is INTEGER-POSITION-based — use 0-based integer positions. With slicing: .loc[0:3] INCLUDES 3; .iloc[0:3] EXCLUDES 3.' },
  { id:'pd2-j1', experienceLevel:'junior', type:'practical', question:'How do you group by multiple columns and apply multiple aggregations?', answer:'Use named aggregation with agg() for clear results.', code:"result = df.groupby(['department', 'city']).agg(\n    avg_salary=('salary', 'mean'),\n    headcount=('salary', 'count'),\n).reset_index()" },
  { id:'pd2-m1', experienceLevel:'mid', type:'conceptual', question:'What is vectorization in Pandas and why avoid loops?', answer:'Vectorized operations run in C with no Python interpreter overhead per element. A Python loop has tens of microseconds overhead per iteration; vectorized operations process millions of cells in milliseconds. Typically 10-100× faster.' },

  // ─── NumPy ───────────────────────────────────────────────────────────────
  { id:'np2-f3', experienceLevel:'fresher', type:'output', question:'Guess the output', code:'import numpy as np\narr = np.array([10, 20, 30, 40])\nprint(arr * 3)', output:'[30 60 90 120]', explanation:'NumPy broadcasts scalar 3 and multiplies every element — no loop needed.', choices:[{label:'[30 60 90 120]',correct:true},{label:'Repeated array (×3)',correct:false},{label:'Error',correct:false},{label:'120',correct:false}] },
  { id:'np2-j2', experienceLevel:'junior', type:'conceptual', question:'What is the difference between a NumPy view and a copy?', answer:'A view shares the underlying data buffer — modifying it modifies the original. A copy has its own memory. Slicing returns a view. Fancy indexing returns a copy. np.copy() creates an explicit copy.' },
  { id:'np2-j3', experienceLevel:'junior', type:'output', question:'Guess the output', code:'arr = np.array([1, 2, 3])\nb = arr\nb[0] = 99\nprint(arr)', output:'[99  2  3]', explanation:'b = arr is assignment — both variables reference the same NumPy array object.', choices:[{label:'[99  2  3]',correct:true},{label:'[1  2  3] (assignment copies)',correct:false},{label:'Error',correct:false},{label:'[99  99  99]',correct:false}] },

  // ─── Tableau ─────────────────────────────────────────────────────────────
  { id:'tab2-f1', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between a dimension and a measure in Tableau?', answer:'Dimensions (blue): categorical fields used to slice data (Region, Product, Date). Measures (green): quantitative fields automatically aggregated (SUM, AVG) when dragged to the view.' },
  { id:'tab2-f2', experienceLevel:'fresher', type:'conceptual', question:'What is the difference between a live connection and an extract in Tableau?', answer:'Live connection: queries the source in real time — always current but performance depends on source. Extract: a .hyper snapshot in Tableau\'s in-memory engine — extremely fast, must be refreshed for new data.' },
  { id:'tab2-j1', experienceLevel:'junior', type:'conceptual', question:'What is the order of filter execution in Tableau?', answer:'(1) Extract filter, (2) Data Source filter, (3) Context filter, (4) Top N / Conditional filters, (5) Dimension filters, (6) Measure filters. Context filters create a temporary table — subsequent filters run on that restricted set.' },
  { id:'tab2-j3', experienceLevel:'junior', type:'conceptual', question:'What is a Tableau LOD expression and what are the three types?', answer:'LOD expressions compute aggregations at a specified granularity regardless of the view. FIXED: ignores view dimensions and regular filters. INCLUDE: adds extra dimensions to view LOD. EXCLUDE: removes view dimensions.' },
  { id:'tab2-m1', experienceLevel:'mid', type:'conceptual', question:'What is the difference between a calculated field and a table calculation?', answer:'Regular calculated field: computed at data source level before aggregation. Table calculation: computed at visualisation level AFTER aggregation, on query results in memory. Table calcs cannot be used in regular filters.' },

  // ─── Power BI ─────────────────────────────────────────────────────────────
  { id:'pbi2-f1', experienceLevel:'fresher', type:'conceptual', question:'What is DAX and how is it different from Excel formulas?', answer:'DAX is a formula language for Power BI, Power Pivot, and SSAS. Unlike Excel: context-aware (results change based on filters), operates on columns/tables not cells, two types: Calculated Columns (row context) and Measures (filter context), time intelligence functions built-in.' },
  { id:'pbi2-f3', experienceLevel:'fresher', type:'output', question:'What does DIVIDE() return when denominator is 0?', code:'Result = DIVIDE([Numerator], [Denominator], 0)', output:'0 — the third argument (alternate result) is returned instead of division by zero error', explanation:'DIVIDE(num, den, alternate) safely handles division by zero. Without alternate, returns BLANK().', choices:[{label:'0 (the alternate result)',correct:true},{label:'Error in the visual',correct:false},{label:'BLANK()',correct:false},{label:'Infinity',correct:false}] },
  { id:'pbi2-j1', experienceLevel:'junior', type:'conceptual', question:'What is filter context vs row context in DAX?', answer:'Filter context: the set of active filters from slicers and report visuals — measures evaluate here. Row context: the current row being evaluated in a calculated column or iterator (SUMX, AVERAGEX). CALCULATE() creates a new filter context.' },
  { id:'pbi2-j3', experienceLevel:'junior', type:'conceptual', question:'What is a Star Schema and why is it recommended for Power BI?', answer:'Star Schema: one central fact table connected to dimension tables with one-to-many relationships. Benefits: simple model, better VertiPaq performance, predictable filter propagation. Avoid wide flat tables and snowflake schemas in Power BI.' },
  { id:'pbi2-m1', experienceLevel:'mid', type:'conceptual', question:'What is the CALCULATE function and how does context transition work?', answer:'CALCULATE(expression, filters) evaluates expression in a modified filter context. Context transition: when called inside a row context (calculated column), it converts the row context into an equivalent filter context automatically.' },
];

// ── Seed function ────────────────────────────────────────────────────────────
async function seed() {
  console.log('Connecting to MongoDB...');
  await mongoose.connect(MONGO_URI);
  console.log(`Connected to: ${MONGO_URI}`);

  let inserted = 0;
  let updated  = 0;
  let errors   = 0;

  for (let i = 0; i < RAW_QUESTIONS.length; i++) {
    const raw = RAW_QUESTIONS[i];
    const topicId = deriveTopicId(raw.id);
    const trackId = TOPIC_MAP[topicId] ?? 'mern-stack';

    const doc = {
      questionId:      raw.id,
      topicId,
      trackId,
      experienceLevel: raw.experienceLevel,
      type:            raw.type,
      question:        raw.question,
      answer:          raw.answer,
      code:            raw.code        ?? '',
      explanation:     raw.explanation ?? '',
      output:          raw.output      ?? '',
      choices:         raw.choices     ?? [],
      order:           i,
      isActive:        true,
    };

    try {
      const result = await Question.updateOne(
        { questionId: raw.id },
        { $set: doc },
        { upsert: true }
      );
      if (result.upsertedCount) inserted++;
      else if (result.modifiedCount) updated++;
    } catch (err) {
      console.error(`  ✗ Failed: ${raw.id} — ${err.message}`);
      errors++;
    }
  }

  console.log('\n────────────────────────────────');
  console.log(`✅ Seed complete:`);
  console.log(`   Inserted: ${inserted}`);
  console.log(`   Updated:  ${updated}`);
  console.log(`   Errors:   ${errors}`);
  console.log(`   Total:    ${RAW_QUESTIONS.length}`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
